# Generated by Django 5.2 on 2025-05-05 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='API密钥')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('allowed_ips', models.TextField(blank=True, help_text='多个IP地址请用逗号分隔，留空表示不限制', null=True, verbose_name='允许的IP地址')),
                ('rate_limit_override', models.IntegerField(blank=True, help_text='每分钟请求数，覆盖接口默认限制，留空表示使用接口默认限制', null=True, verbose_name='速率限制覆盖')),
                ('call_count', models.IntegerField(default=0, verbose_name='调用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API密钥',
                'verbose_name_plural': 'API密钥管理',
            },
        ),
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='接口描述')),
                ('path', models.CharField(max_length=255, verbose_name='接口路径')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='请求方法')),
                ('status', models.CharField(choices=[('active', '活跃'), ('deprecated', '已弃用'), ('maintenance', '维护中')], default='active', max_length=20, verbose_name='状态')),
                ('permission', models.CharField(choices=[('public', '公开'), ('authenticated', '需要认证'), ('admin', '仅管理员')], default='authenticated', max_length=20, verbose_name='权限要求')),
                ('request_schema', models.JSONField(blank=True, default=dict, null=True, verbose_name='请求参数配置')),
                ('response_schema', models.JSONField(blank=True, default=dict, null=True, verbose_name='响应参数配置')),
                ('rate_limit', models.IntegerField(default=60, help_text='每分钟允许的最大请求次数', verbose_name='速率限制(每分钟)')),
                ('call_count', models.IntegerField(default=0, verbose_name='调用次数')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误次数')),
                ('average_response_time', models.FloatField(default=0, verbose_name='平均响应时间(毫秒)')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API接口',
                'verbose_name_plural': 'API接口管理',
                'ordering': ['path'],
                'unique_together': {('path', 'method', 'version')},
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='用户代理')),
                ('request_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='请求数据')),
                ('status_code', models.IntegerField(verbose_name='响应状态码')),
                ('response_time', models.FloatField(verbose_name='响应时间(毫秒)')),
                ('response_size', models.IntegerField(default=0, verbose_name='响应大小(字节)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户ID')),
                ('api_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='API密钥')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apiendpoint', verbose_name='调用的接口')),
            ],
            options={
                'verbose_name': 'API调用日志',
                'verbose_name_plural': 'API调用日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
