# Generated by Django 5.2 on 2025-05-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='知识库名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('document_count', models.IntegerField(default=0, verbose_name='文档数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '提示词模板',
                'verbose_name_plural': '提示词模板',
            },
        ),
        migrations.CreateModel(
            name='ServiceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止')], default='stopped', max_length=20, verbose_name='状态')),
                ('command', models.CharField(max_length=255, verbose_name='启动命令')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='进程ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '服务控制',
                'verbose_name_plural': '服务控制',
            },
        ),
    ]
