# Generated by Django 5.2 on 2025-05-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='文档内容'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文件路径'),
        ),
    ]
