# Generated by Django 5.2 on 2025-05-04 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_knowledgebase_content_knowledgebase_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('model_path', models.CharField(max_length=255, verbose_name='模型路径')),
                ('device', models.CharField(choices=[('cuda', 'GPU'), ('cpu', 'CPU')], default='cuda', max_length=20, verbose_name='设备')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('batch_size', models.IntegerField(default=1, verbose_name='批处理大小')),
                ('precision', models.CharField(choices=[('float16', '半精度'), ('float32', '全精度')], default='float16', max_length=20, verbose_name='精度')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模型配置',
                'verbose_name_plural': '模型配置',
            },
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='embedding_model',
            field=models.CharField(default='text-embedding-ada-002', max_length=100, verbose_name='嵌入模型'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='is_indexed',
            field=models.BooleanField(default=False, verbose_name='是否已向量化'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='vector_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='向量数据'),
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='分块内容')),
                ('vector_data', models.BinaryField(blank=True, null=True, verbose_name='向量数据')),
                ('is_indexed', models.BooleanField(default=False, verbose_name='是否已向量化')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.knowledgebase', verbose_name='所属知识库')),
            ],
            options={
                'verbose_name': '知识分块',
                'verbose_name_plural': '知识分块',
                'ordering': ['knowledge_base', 'id'],
            },
        ),
    ]
