# Generated by Django 5.2 on 2025-05-04 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VectorIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='索引名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('document_count', models.IntegerField(default=0, verbose_name='文档数量')),
                ('vector_dimension', models.IntegerField(default=384, verbose_name='向量维度')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('vector_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='向量文件路径')),
                ('metadata_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='元数据文件路径')),
            ],
            options={
                'verbose_name': '向量索引',
                'verbose_name_plural': '向量索引',
            },
        ),
        migrations.CreateModel(
            name='DocumentVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=100, verbose_name='文档ID')),
                ('source', models.CharField(max_length=100, verbose_name='来源')),
                ('text', models.TextField(verbose_name='文本内容')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='元数据')),
                ('embedding_updated', models.DateTimeField(auto_now=True, verbose_name='向量更新时间')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vector_search.vectorindex', verbose_name='所属索引')),
            ],
            options={
                'verbose_name': '文档向量',
                'verbose_name_plural': '文档向量',
                'unique_together': {('index', 'document_id')},
            },
        ),
    ]
